### ISSUE TITLE
[Suggestion] Add calculation by monthly interest and add months installments

### ISSUE THREAD

**Issue by rafaell-lycan** [kfiku/LoanJS#13]
Hey @kfiku, in Brazil loans are calculated by months, both installments and the interest.

Is it possible to adapt as an option installments year and month? Like 18 months `installmentYear: 1` and `installmentMonth: 6`, and then, add an option to use the interest based on monthly or annual.

I really liked the lib, I'll try to figure out this week how to adapt and make a pull request.

**Comment by kfiku** [comment]
I thing i can do it. I will try to add it this week.

**Comment by kfiku** [comment]
Hi, it is good explanation of the topic? http://brazilianmarketfordummies.blogspot.com/2017/07/how-to-calculate-interests-in-brazil.html

And how People pay loan: per month with sum of interests from this table: https://1.bp.blogspot.com/-fO1tSrIDXHU/WVwH1a0wMyI/AAAAAAAAA_0/cENadzhjlvIZMJraJKGq2znqanoTuyMGgCLcBGAs/s1600/PerCDI%2Bnumeric%2Bexample%2B-%2Btable.jpg

So it should be also shown in returning value of new Lona in every `installment`?


thanks

**Comment by rafaell-lycan** [comment]
@kfiku sorry the delay, but yes, it's right the information.

I put some extra logic at the platform that I work, but I'd like to check your implementation.

**Comment by rafaell-lycan** [comment]
[I found this project in Github that has the same propose](https://github.com/valencar/tax_easy)

**Comment by kfiku** [comment]
@rafaell-lycan so it should be count  with constant interest rate, or it should be provided by every day or randomize? In lib that you send me its using constant interest rate.

**Comment by rafaell-lycan** [comment]
@kfiku we implemented as a constant.
